disabled_rules:
  - trailing_whitespace
  - todo
  - identifier_name

identifier_name:
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
    - id
    - URL
    - url
    - app


excluded:
  - Carthage
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - Source/*/ExcludedFile.swift
  - Pods
