# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'MatcHair' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MatcHair

   pod 'Bolts'
   pod 'FBSDKCoreKit'
   pod 'FBSDKShareKit'
   pod 'FBSDKLoginKit'
   pod 'SwiftLint'
   pod 'Firebase/Core'
   pod 'Firebase/Auth'
   pod 'Firebase/Storage'
   pod 'FirebaseDatabase'
   pod 'Kingfisher', '~> 4.0'
   pod 'DatePickerDialog'
   pod 'IQKeyboardManagerSwift'
   pod 'Fabric'
   pod 'Crashlytics'
   pod 'lottie-ios'

   

end
